name: brd_issue_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  syncfusion_flutter_charts: ^20.4.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
