// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHsXNtOx0SVb4L0nPugOms4R7Xb-rT7w',
    appId: '1:592080882001:web:87c03a75ef7ce8c8e1eb70',
    messagingSenderId: '592080882001',
    projectId: 'issue-tracker-d6afe',
    authDomain: 'issue-tracker-d6afe.firebaseapp.com',
    storageBucket: 'issue-tracker-d6afe.appspot.com',
    measurementId: 'G-X0F5MS7SFW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbxA1oUkQK4UFsjZXzcKlvcoiCom6E6CI',
    appId: '1:592080882001:ios:5ae9a2c426dd5be7e1eb70',
    messagingSenderId: '592080882001',
    projectId: 'issue-tracker-d6afe',
    storageBucket: 'issue-tracker-d6afe.appspot.com',
    iosClientId: '592080882001-u10lu2f2i6lk3u81ib0bhlma31tgorbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.brdIssueTracker',
  );
}
